#!/bin/sh

mkdir -p php/includes
cp bsonarrayobj.h php/includes/
cp bsondefs.h php/includes/
cp bsoncontent.h php/includes/
cp bson.h php/includes/
cp bsonobj.h php/includes/
cp bsonparser.h php/includes/
cp bsonutil.h php/includes/
cp djondbconnection.h php/includes/
cp djondb_client.h php/includes/
cp djondbconnectionmanager.h php/includes/
cp djonv8.h php/includes/
cp constantexpression.h php/includes/
cp expressionresult.h php/includes/
cp dbcontroller.h php/includes/
cp db.h php/includes/
cp filterdefs.h php/includes/
cp filter_expressionLexer.h php/includes/
cp filter_expressionParser.h php/includes/
cp filterparser.h php/includes/
cp indexfactory.h php/includes/
cp index.h php/includes/
cp indexmanager.h php/includes/
cp simpleexpression.h php/includes/
cp streammanager.h php/includes/
cp unaryexpression.h php/includes/
cp baseexpression.h php/includes/
cp binaryexpression.h php/includes/
cp bplusindex.h php/includes/
cp logger.h php/includes/
cp settings.h php/includes/
cp stringfunctions.h php/includes/
cp threads.h php/includes/
cp util.h php/includes/
cp version.h php/includes/
cp defs.h php/includes/
cp datetime.h php/includes/
cp dtime.h php/includes/
cp errorhandle.h php/includes/
cp djon_error_codes.h php/includes/
cp fileutil.h php/includes/
cp circular_queue.h php/includes/
cp config.h php/includes/

