cp ../../includes/bsonarrayobj.h .
cp ../../includes/bsondefs.h .
cp ../../includes/bsoncontent.h .
cp ../../includes/bson.h .
cp ../../includes/bsonobj.h .
cp ../../includes/bsonparser.h .
cp ../../includes/bsonutil.h .
cp ../../includes/djondbconnection.h .
cp ../../includes/djondb_client.h .
cp ../../includes/djondbconnectionmanager.h .
cp ../../includes/constantexpression.h .
cp ../../includes/expressionresult.h .
cp ../../includes/dbcontroller.h .
cp ../../includes/db.h .
cp ../../includes/filterdefs.h .
cp ../../includes/filter_expressionLexer.h .
cp ../../includes/filter_expressionParser.h .
cp ../../includes/filterparser.h .
cp ../../includes/indexfactory.h .
cp ../../includes/index.h .
cp ../../includes/indexmanager.h .
cp ../../includes/simpleexpression.h .
cp ../../includes/streammanager.h .
cp ../../includes/unaryexpression.h .
cp ../../includes/baseexpression.h .
cp ../../includes/binaryexpression.h .
cp ../../includes/bplusindex.h .
cp ../../includes/logger.h .
cp ../../includes/settings.h .
cp ../../includes/stringfunctions.h .
cp ../../includes/threads.h .
cp ../../includes/util.h .
cp ../../includes/version.h .
cp ../../includes/defs.h .
cp ../../includes/datetime.h .
cp ../../includes/dtime.h .
cp ../../includes/errorhandle.h .
cp ../../includes/djon_error_codes.h .
cp ../../includes/fileutil.h .
cp ../../includes/circular_queue.h .
cp ../../includes/config.h .
