/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/cross/workspace/djondb_tx/db/grammars/bson_grammar.g
 *     -                            On : 2013-05-25 21:32:07
 *     -                 for the lexer : bson_grammarLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
bson_grammarLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pbson_grammarLexer, which is returned from a call to bson_grammarLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pbson_grammarLexer are  as follows:
 *
 *  - 
 void
      pbson_grammarLexer->TRUE(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->FALSE(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->NUMBER(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->FLOAT(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->WS(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->COMMENT(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->ID(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->STRING(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->EXPONENT(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->HEX_DIGIT(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->ESC_SEQ(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->OCTAL_ESC(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->UNICODE_ESC(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->COMMA(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->LPAREN(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->RPAREN(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->LBRAN(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->RBRAN(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->LBRAK(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->RBRAK(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->COLON(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->SEMICOLON(pbson_grammarLexer)
 *  - 
 void
      pbson_grammarLexer->Tokens(pbson_grammarLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_bson_grammarLexer_H
#define _bson_grammarLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct bson_grammarLexer_Ctx_struct bson_grammarLexer, * pbson_grammarLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
bson_grammarLexer

 */
struct bson_grammarLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mTRUE)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mFALSE)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mNUMBER)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mFLOAT)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mEXPONENT)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mHEX_DIGIT)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mESC_SEQ)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mOCTAL_ESC)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mUNICODE_ESC)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mCOMMA)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mLPAREN)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mRPAREN)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mLBRAN)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mRBRAN)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mLBRAK)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mRBRAK)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mCOLON)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mSEMICOLON)	(struct bson_grammarLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct bson_grammarLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct bson_grammarLexer_Ctx_struct * ctx);
    void	    (*free)   (struct bson_grammarLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pbson_grammarLexer bson_grammarLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pbson_grammarLexer bson_grammarLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define COLON      4
#define COMMA      5
#define COMMENT      6
#define ESC_SEQ      7
#define EXPONENT      8
#define FALSE      9
#define FLOAT      10
#define HEX_DIGIT      11
#define ID      12
#define LBRAK      13
#define LBRAN      14
#define LPAREN      15
#define NUMBER      16
#define OCTAL_ESC      17
#define RBRAK      18
#define RBRAN      19
#define RPAREN      20
#define SEMICOLON      21
#define STRING      22
#define TRUE      23
#define UNICODE_ESC      24
#define WS      25
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for bson_grammarLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
