dependencies:
	mkdir -p third_party/libs
	mkdir -p third_party/includes

	#build libantlr
	cd third_party; sh buildantlr.sh
	
	# build libgtest
	cd third_party; sh buildgtest.sh	

	# build v8
	cd third_party; sh buildv8.sh	
